BEGIN:
	start ./p0_base/main.cpp
	start ./p1_test/main.cpp
	start ./p2_range/main.cpp
	start ./p3_allocator/main.cpp
	start ./p4_dynamic/main.cpp
	start ./p5_random/main.cpp
	start ./p6_algorithm/main.cpp
	start ./p7_algorithm_by_range/main.cpp
	start ./p8_algorithm_by_range_2/main.cpp
	start ./p9_algorithm_by_range_3/main.cpp
	start ./p10_basic_string/main.cpp
	start ./p11_sso_string/main.cpp
	start ./p12_bitset/main.cpp
	start ./p13_vector/main.cpp
	start ./p14_vector_bool/main.cpp
	start ./p15_local_vector/main.cpp
	start ./p16_small_vector/main.cpp
	start ./p17_pointer_vector/main.cpp
	start ./p18_circular_vector/main.cpp
	start ./p19_deque/main.cpp
	start ./p20_forward_list/main.cpp
	start ./p21_list/main.cpp
	start ./p22_stack_and_queue/main.cpp
	start ./p23_flat_map/main.cpp
	start ./p24_rb_map/main.cpp
	start ./p25_avl_map/main.cpp
	start ./p26_ranked_map/main.cpp
	start ./p27_unordered_map/main.cpp
	start ./p28_mixed_map/main.cpp
	start ./p29_stable_vector/main.cpp
	start ./p30_tree/main.cpp
	start ./p31_limited_tree/main.cpp
	start ./p32_linked_tree/main.cpp
	start ./p33_logn_tree/main.cpp
       	start ./p34_time/main.cpp
       	start ./p35_io/main.cpp
       	start ./p36_concurrency/main.cpp
