copy makefile ..\p00_base
copy makefile ..\p01_test
copy makefile ..\p02_range
copy makefile ..\p03_allocator
copy makefile ..\p04_dynamic
copy makefile ..\p05_random
copy makefile ..\p06_algorithm
copy makefile ..\p07_algorithm_by_range
copy makefile ..\p08_algorithm_by_range_2
copy makefile ..\p09_algorithm_by_range_3
copy makefile ..\p10_basic_string
copy makefile ..\p11_sso_string
copy makefile ..\p12_bitset
copy makefile ..\p13_vector
copy makefile ..\p14_vector_bool
copy makefile ..\p15_local_vector
copy makefile ..\p16_small_vector
copy makefile ..\p17_pointer_vector
copy makefile ..\p18_circular_vector
copy makefile ..\p19_deque
copy makefile ..\p20_forward_list
copy makefile ..\p21_list
copy makefile ..\p22_stack_and_queue
copy makefile ..\p23_flat_map
copy makefile ..\p24_rb_map
copy makefile ..\p25_avl_map
copy makefile ..\p26_ranked_map
copy makefile ..\p27_unordered_map
copy makefile ..\p28_mixed_map
copy makefile ..\p29_stable_vector
copy makefile ..\p30_tree
copy makefile ..\p31_limited_tree
copy makefile ..\p32_linked_tree
copy makefile ..\p33_logn_tree
copy makefile ..\p34_matrix
copy makefile ..\p35_dup_compressed_array
copy makefile ..\p36_time
copy makefile ..\p37_io
copy makefile ..\p38_concurrency
