copy makefile ..\p0_base
copy makefile ..\p1_test
copy makefile ..\p2_range
copy makefile ..\p3_allocator
copy makefile ..\p4_dynamic
copy makefile ..\p5_random
copy makefile ..\p6_algorithm
copy makefile ..\p7_algorithm_by_range
copy makefile ..\p8_algorithm_by_range_2
copy makefile ..\p9_algorithm_by_range_3
copy makefile ..\p10_basic_string
copy makefile ..\p11_sso_string
copy makefile ..\p12_bitset
copy makefile ..\p13_vector
copy makefile ..\p14_vector_bool
copy makefile ..\p15_local_vector
copy makefile ..\p16_small_vector
copy makefile ..\p17_pointer_vector
copy makefile ..\p18_circular_vector
copy makefile ..\p19_deque
copy makefile ..\p20_forward_list
copy makefile ..\p21_list
copy makefile ..\p22_stack_and_queue
copy makefile ..\p23_flat_map
copy makefile ..\p24_rb_map
copy makefile ..\p25_avl_map
copy makefile ..\p26_ranked_map
copy makefile ..\p27_unordered_map
copy makefile ..\p28_mixed_map
copy makefile ..\p29_stable_vector
copy makefile ..\p30_tree
copy makefile ..\p31_limited_tree
copy makefile ..\p32_linked_tree
copy makefile ..\p33_logn_tree
copy makefile ..\p34_io
